// <auto-generated />
namespace FRTools.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedpreviewtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedpreviewtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201812102238126_Added preview table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
