// <auto-generated />
namespace FRTools.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Pinglistcategorytables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pinglistcategorytables));
        
        string IMigrationMetadata.Id
        {
            get { return "201911080632431_Pinglistcategory tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
