// <auto-generated />
namespace FRTools.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class flashsaletracker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(flashsaletracker));
        
        string IMigrationMetadata.Id
        {
            get { return "202103251044067_flash sale tracker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
