//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRTools.Discord {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FRTools.Discord.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAgZ3pUWHRSYXcgcHJvZmlsZSB0eXBlIGV4aWYAAHja7ZxZclw5cEX/sQovAfOwHIwR3oGX73NRVeIgUi21/GFHuBUiqeIrPLxE5h0SqDb7v/7zmP/gv2ZLNDGVmlvOlv9ii813fqj28d/ju7Pxfn39555fP7xufvzo+R74Hh6/yPv5rs7r6e0NJT5fHx9fN2U+fvD1OdDrzs8Bg+7s+eF5XX0OFPzjdff8t2nP9/X47nGef8/099dpPH71+d+xEIyVGC9443dwwfK16i7h8bfz1/HVB+c/vhJC/jp25rvgfRc725+vh4+hMDY/L8ifYvR83aWvY3cj9H5G7u3OH36Rpvf2/X/vY3dWPWc/nq7HTKSyeT7U61HuT1xIOGO4b8v8KfxN/Fzun8afyiNOVmyxmoM/07jmPNE+Lrrlujtu3+/TTaYY/faF795P4q7Xaii++XlDH/XHHV9CC8uE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DominanceModuleIcon {
            get {
                return ResourceManager.GetString("DominanceModuleIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/uvFuIJz.gif.
        /// </summary>
        internal static string DominanceSetup_0 {
            get {
                return ResourceManager.GetString("DominanceSetup_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command is used to set up the entire dominance module in one go. You can set up each individual role using the website as well if you do not want to use this wizard. {0} This image makes totally no sense, but then again it is just an example after all..
        /// </summary>
        internal static string DominanceSetupDetailed {
            get {
                return ResourceManager.GetString("DominanceSetupDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command is used to set up the entire dominance module in one go. You can set up each individual role using the website as well if you do not want to use this wizard..
        /// </summary>
        internal static string DominanceSetupSynopsis {
            get {
                return ResourceManager.GetString("DominanceSetupSynopsis", resourceCulture);
            }
        }
    }
}
